popmachine/application/blueprints/account.py
from ..forms import SearchForm, RegisterForm, LoginForm
from ..app import mail
from ..safeurl import is_safe_url
from popmachine import models

from sqlalchemy import not_, or_
import flask
from flask import Blueprint, current_app, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user, logout_user
from flask_mail import Message

profile = Blueprint('account', __name__)


@profile.route('/register', methods=["GET", "POST"])
def create_account():
    searchform = SearchForm()
    form = RegisterForm()
    if form.validate_on_submit():
        if form.password.data != form.password_confirm.data:
            flask.flash('passwords do not match!')
            return redirect(url_for('account.create_account'), method='GET')

        # check for existing username or emails
        users = current_app.machine.session.query(models.User).filter(
            or_(
                models.User.username == form.username.data,
                models.User.email == form.email.data,
            )
        )
        if users.count() > 0:
            flask.flash('account already exists with username and/or email!')
            return redirect(url_for('account.create_account'), method='GET')

        user = models.User(
            name=form.name.data,
            username=form.username.data,
            email=form.email.data,
            password=form.password.data.encode('utf-8')
        )
        current_app.machine.session.add(user)
        current_app.machine.session.commit()

        # Now we'll send the email confirmation link
        subject = "Confirm your email"

        token = current_app.ts.dumps(user.email, salt='email-confirm-key')

        confirm_url = url_for(
            'account.confirm_email',
            token=token,
            _external=True)

        html = render_template(
            'accounts/email-activate.html',
            confirm_url=confirm_url, searchform=searchform)

        msg = Message(subject,
                      sender="popmachine.db@gmail.com",
                      recipients=[user.email], html=html)
        mail.send(msg)

        # print user.email, html
        flask.flash(
            'account created, please check your email for verification.')

        return redirect(url_for("misc.index"))

    return render_template("accounts/create.html", form=form, searchform=searchform)


@profile.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = current_app.ts.loads(
            token, salt="email-confirm-key", max_age=86400)

        user = current_app.machine.session.query(models.User).filter_by(
            email=email).one_or_none()
    except:
        abort(404)

    if user is None:
        flask.abort(404)

    user.email_confirmed = True

    current_app.machine.session.add(user)
    current_app.machine.session.commit()

    return redirect(url_for('misc.index'))


@profile.route('/login', methods=['GET', 'POST'])
def login():

    searchform = SearchForm()
    # Here we use a class of some kind to represent and validate our
    # client-side form data. For example, WTForms is a library that will
    # handle this for us, and we use a custom LoginForm to validate.
    form = LoginForm()
    if form.validate_on_submit():

        user = current_app.machine.session.query(models.User).filter_by(
            username=request.form['name']).one_or_none()

        if user is None or not user.is_correct_password(str(request.form['password'])):
            flask.flash('Incorrect username or password.')
            return flask.redirect(flask.url_for('account.login', form=form, method='GET'))

        login_user(user)

        flask.flash('Logged in successfully.')

        next = flask.request.args.get('next')
        if not is_safe_url(next):
            return flask.abort(400)

        return flask.redirect(next or flask.url_for('misc.index'))
    return flask.render_template('login.html', form=form, searchform=searchform)


@profile.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('misc.index'))

popmachine/application/blueprints/design.py
from ..forms import SearchForm, DesignForm
from ..plot import plotDataset
from popmachine import models

from sqlalchemy import not_, or_
import flask
from flask import Blueprint, current_app, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from wtforms import TextAreaField

profile = Blueprint('design', __name__)


@profile.route('/designs/')
def designs():
    if current_user.is_authenticated:
        designs = current_app.machine.session.query(models.Design).join(models.Project).filter(
            or_(models.Project.published, models.Project.owner == current_user)).all()
    else:
        designs = current_app.machine.session.query(models.Design).join(
            models.Project).filter(models.Project.published).all()
    searchform = SearchForm()

    return render_template("designs.html", designs=designs, searchform=searchform)


@profile.route('/design/<_id>', methods=['GET'])
@profile.route('/design/<_id>/<plate>')
def design(_id, plate=None):
    searchform = SearchForm()
    designform = DesignForm()

    design = current_app.machine.session.query(models.Design)\
        .filter(models.Design.id == _id).one_or_none()

    designform.type.default = design.type
    designform.process()

    if request.method == 'GET':

        designform.type.default = design.type

        values = current_app.machine.session.query(models.ExperimentalDesign)\
            .join(models.Design)\
            .filter(models.Design.id == _id)

        wells = current_app.machine.session.query(models.Well)\
            .join(models.well_experimental_design)\
            .join(models.ExperimentalDesign)\
            .join(models.Design)\
            .filter(models.Design.id == _id)

        if not plate is None:
            wells = wells.join(models.Plate).filter(models.Plate.name == plate)

            values = values.join(models.well_experimental_design)\
                .join(models.Well)\
                .join(models.Plate).filter(models.Plate.name == plate)

        if wells.count() < 200:

            ds = current_app.machine.get(wells, include=[design.name])

            assert not any(ds.meta[design.name].isnull())

            color = map(lambda x: ds.meta[design.name].unique(
            ).tolist().index(x), ds.meta[design.name])

            return plotDataset(ds, 'design.html', color=ds.meta[design.name], values=values, design=design,
                               searchform=searchform, plate=plate, designform=designform)

        return render_template('design.html',  values=values, design=design,
                               searchform=searchform, plate=plate, designform=designform)

    else:
        design.type = request.form['type']
        current_app.machine.session.commit()

        return redirect(url_for('design.design', _id=design.id))


@profile.route('/design_edit/<_id>', methods=['GET', 'POST'])
@login_required
def design_edit(_id):

    searchform = SearchForm()

    design = current_app.machine.session.query(models.Design)\
        .filter(models.Design.id == _id).one_or_none()

    class DynamicDesignForm(DesignForm):

        description = TextAreaField('description', default=design.description)
        protocol = TextAreaField('protocol', default=design.protocol)

    designform = DynamicDesignForm()

    designform.type.default = design.type
    designform.description.default = design.description
    designform.protocol.default = design.protocol
    designform.process()

    if request.method == 'GET':

        return render_template('design-edit.html', searchform=searchform, designform=designform, design=design)

    else:
        design.type = request.form['type']
        design.description = request.form['description']
        design.protocol = request.form['protocol']
        current_app.machine.session.commit()

        return redirect(url_for('design.design', _id=design.id))

popmachine/application/blueprints/plate.py
from ..forms import SearchForm, PlateCreate
from popmachine import models, bioscreen

from sqlalchemy import not_, or_
import flask
from flask import Blueprint, current_app, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from wtforms import SelectField

import pandas as pd

profile = Blueprint('plate', __name__)


@profile.route('/plates/')
def plates():

    if current_user.is_authenticated:
        plates = current_app.machine.session.query(models.Plate).join(models.Project).filter(
            or_(models.Project.published, models.Project.owner == current_user)).all()
    else:
        plates = current_app.machine.session.query(models.Plate).join(
            models.Project).filter(models.Project.published).all()

    searchform = SearchForm()

    return render_template("plates.html", plates=plates, searchform=searchform)


@profile.route('/plate/<platename>')
def plate(platename):
    searchform = SearchForm()
    plate = current_app.machine.session.query(models.Plate).filter(
        models.Plate.name == platename).one_or_none()

    experimentalDesigns = current_app.machine.session.query(models.ExperimentalDesign)\
        .join(models.well_experimental_design)\
        .join(models.Well)\
        .filter(models.Well.id.in_([w.id for w in plate.wells]))

    designs = current_app.machine.session.query(models.Design)\
        .join(models.ExperimentalDesign)\
        .join(models.well_experimental_design)\
        .join(models.Well)\
        .filter(models.Well.id.in_([w.id for w in plate.wells]))

    return render_template("plate.html", plate=plate, experimentalDesigns=experimentalDesigns, designs=designs, searchform=searchform)


@profile.route('/plate-delete/<platename>', methods=['GET', 'POST'])
def plate_delete(platename):
    searchform = SearchForm()

    if request.method == 'GET':
        return render_template('plate-delete.html', searchform=searchform, platename=platename)
    else:
        plate = current_app.machine.session.query(models.Plate).filter(
            models.Plate.name == platename).one_or_none()
        current_app.machine.deletePlate(plate.project, plate)

        return redirect(url_for('plate.plates'))


@profile.route('/plate-create/', methods=['GET', "POST"])
@login_required
def plate_create():

    searchform = SearchForm()

    myprojects = current_app.machine.session.query(
        models.Project).filter_by(owner=current_user).all()

    class DynamicPlateCreate(PlateCreate):
        project = SelectField("project", choices=[
                              (p.name, p.name) for p in myprojects])

    if request.method == "GET":
        form = DynamicPlateCreate()
        return render_template("plate-create.html", form=form, searchform=searchform)
    else:

        project = current_app.machine.session.query(models.Project).filter_by(
            owner=current_user, name=request.form['project']).one_or_none()

        name = request.form['name']
        ignore = request.form['ignore'].split(",")
        f = request.files['data']
        data = pd.read_csv(f)

        if 'design' in request.files:
            f = request.files['design']
            meta = pd.read_csv(f)

            if len(ignore) > 0:
                for i in ignore:
                    if i == "":
                        continue
                    del meta[i]
        else:
            meta = None

        if request.form['source'] == 'csv':
            plate = current_app.machine.createPlate(project, name, data, meta)
        elif request.form['source'] == 'bioscreen':
            data = bioscreen.parse(data)
            plate = current_app.machine.createPlate(project, name, data, meta)
        else:
            flask.flash('only csv source supported currently!')
            pass

        return redirect(url_for('plate.plates'))

popmachine/application/blueprints/project.py
from ..forms import SearchForm, ProjectForm
from popmachine import models

import datetime

from sqlalchemy import not_
import flask
from flask import Blueprint, current_app, render_template, redirect, url_for, request
from flask_login import login_required, current_user

profile = Blueprint('project', __name__)


@profile.route('/project/<projectid>')
def project(projectid):
    searchform = SearchForm()
    project = current_app.machine.session.query(
        models.Project).filter_by(id=projectid).one_or_none()

    if not project or (not project.published and (not current_user.is_authenticated or project.owner != current_user)):
        flask.flash(
            'project not found or you do not have permissions to view it!')
        return redirect(url_for('misc.index'))

    return render_template("project.html", project=project, searchform=searchform)


@profile.route('/projects/')
def projects():

    if not current_user.is_authenticated:
        myprojects = None
        projects = current_app.machine.session.query(
            models.Project).filter_by(published=True)
    else:
        myprojects = current_app.machine.session.query(
            models.Project).filter_by(owner=current_user)
        projects = current_app.machine.session.query(models.Project).filter_by(
            published=True).filter(not_(models.Project.owner == current_user))

    searchform = SearchForm()

    return render_template("projects.html", myprojects=myprojects, searchform=searchform, projects=projects)


@profile.route('/project/<projectid>/publish')
@login_required
def project_publish(projectid):

    project = current_app.machine.session.query(models.Project).filter_by(
        id=projectid, owner=current_user).one_or_none()

    if project:

        project.published = True
        current_app.machine.session.add(project)
        current_app.machine.session.commit()

        return redirect((url_for('project.project', projectid=project.id)))

    return redirect(url_for('project.projects'))


@profile.route('/project/<projectid>/unpublish')
@login_required
def project_unpublish(projectid):

    project = current_app.machine.session.query(models.Project).filter_by(
        id=projectid, owner=current_user).one_or_none()

    if project:

        project.published = False
        current_app.machine.session.add(project)
        current_app.machine.session.commit()

        return redirect((url_for('project.project', projectid=project.id)))

    return redirect(url_for('project.projects'))


@profile.route('/project/<projectid>/edit', methods=['GET', 'POST'])
@login_required
def project_edit(projectid):

    project = current_app.machine.session.query(models.Project).filter_by(
        id=projectid, owner=current_user).one_or_none()

    if project:

        searchform = SearchForm()
        form = ProjectForm()

        form.name.data = project.name
        form.description.data = project.description
        form.design.data = project.design
        form.published.data = project.published
        form.citation_pmid.data = project.citation_pmid

        if request.method == "GET":
            return render_template("project-form.html", form=form, searchform=searchform, redirect=url_for('project.project_edit', projectid=project.id))
        else:

            project.name = request.form['name']
            project.description = request.form['description']
            project.design = request.form['design']
            project.published = 'published' in request.form and request.form['published']
            project.citation = request.form['citation']
            project.citation_pmid = request.form['citation_pmid']

            current_app.machine.session.add(project)
            current_app.machine.session.commit()

    flask.flash('no project found!')
    return redirect(url_for('project.projects'))


@profile.route('/project-create/', methods=['GET', "POST"])
@login_required
def project_create():

    searchform = SearchForm()
    form = ProjectForm(request.form)

    if form.validate_on_submit():

        name = form.name.data
        description = form.description.data
        design = form.design.data
        citation = form.citation.data
        citation_pmid = form.citation_pmid.data

        now = datetime.datetime.now()

        project = models.Project(name=name, description=description, design=design, published=False, citation_text=citation,
                                 citation_pmid=citation_pmid, owner=current_user, submission_date=now, modified_date=now)
        current_app.machine.session.add(project)
        current_app.machine.session.commit()

        return redirect(url_for('project.project', projectid=project.id))

    return render_template("project-create.html", form=form, searchform=searchform)

popmachine/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <!-- Latest compiled and minified CSS -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
      <link href="{{url_for('static', filename='sticky-footer.css')}}" rel="stylesheet">
      <link rel="shortcut icon" href="{{ url_for('static', filename='flask-small.ico') }}">

      <script type="text/javascript" src="/media/main.js"></script>
      {% block head %}{% endblock %}
      <title>popmachine</title>
  </head>

  <body>

    <div class='container'>
      <div class="page-header">
        <h1><a href="{{url_for('misc.index')}}">popmachine</a> <small> {% block subheading %}{% endblock %} </small></h1>
      </div>
    </div>

<!-- <div class='container'> -->
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img height=30px alt="Brand" src="{{url_for("static",filename='flask-small.png')}}"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{{url_for("misc.index")}}">Home</a></li>
            <li><a href="{{url_for('project.projects')}}">Projects</a></li>
            <li><a href="{{url_for('plate.plates')}}">Plates</a></li>
            <li><a href="{{url_for('design.designs')}}">Designs</a></li>
            <!--<li><a href="{{url_for("misc.phenotypes")}}">Phenotypes</a></li>-->
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{{url_for('plate.plate_create')}}">Plate create</a></li>
              </ul>
            </li> -->
          </ul>
          <form class="navbar-form navbar-left" action="{{url_for('misc.search')}}" method='POST'>
            <button type="submit" class="btn btn-default">
               <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
            </button>
            <div class="form-group">
              {{ searchform.search(size=38,placeholder=" e.g. species=E. coli, P. aeruginosa") }}
              <!-- <input type="text" class="form-control" placeholder="Search"> -->
            </div>
            <!-- <button type="submit" class="btn btn-default">Submit</button> -->
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{url_for('misc.index')}}">about</a></li>
            {% if current_user.is_authenticated %}
              <!-- <li class='navbar-brand'></li> -->
              <li><a href="{{url_for('account.logout')}}">log-out</a></li>
            {% else %}
              <li><a href="{{url_for('account.login')}}">log-in</a></li>
            {% endif %}

            {% if current_user.is_authenticated %}
              <li class="navbar-text navbar-right">Hi {{ current_user.name }}!</li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class='container'>
      <div class = 'row'>
        <div id="content" class='col-md-12'>
            {% block fullcontent %}{% endblock %}
        </div>
      </div>
      <div class = 'row'>
        <div id="controls" class='col-md-1'>
            {% block controls %}{% endblock %}
        </div>

        <div id="content" class='col-md-10'>
            {% block content %}{% endblock %}
        </div>

        <div id="content" class='col-md-1'>

          {% with messages = get_flashed_messages() %}
            {% if messages %}
              <h4> messages </h4>
              <!-- <ul class=flashes> -->
              {% for message in messages %}
                <!-- <li>{{ message }}</li> -->
                {{ message }}
              {% endfor %}
              <!-- </ul> -->
            {% endif %}
          {% endwith %}
        </div>
      </div>
      <!-- <div class = 'row'>
        <div id="controls" class='navbar navbar-fixed-bottom'>
            <p class="text-center">&copy; 2017 Peter Tonner</p>
        </div>
      </div> -->
      <!-- <footer class = 'bs-class-footer'>
            &copy; 2017 Peter Tonner
      </footer> -->
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted text-center">&copy; 2017 Peter Tonner</p>
      </div>
    </footer>

  </body>
</html>

popmachine/application/templates/design-edit.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block subheading %}
design edit
{% endblock %}

{% block content %}

<h2> {{design.name}} </h2>

<form action="{{url_for('design.design_edit',_id=design.id)}}" method='POST' enctype="multipart/form-data">
  <div class="form-group">
    <label for="platename">Design type</label>
    {{ designform.type(class_="form-control") }}
  </div>
  <div class="form-group">
    <label>Description</label>
    {{ designform.description(class_="form-control") }}
  </div>
  <div class="form-group">
    <label>Protocol</label>
    {{ designform.protocol(class_="form-control") }}
  </div>
  <button type="submit" id="myButton" class="btn btn-default" data-loading-text="Updating...">
     <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Update
  </button>
  <script>
    $('#myButton').on('click', function () {
      var $btn = $(this).button('loading')
    })
  </script>
</form>

{% endblock %}

popmachine/application/templates/design.html
{% extends "dataset.html" %}

{% block subheading %}
<a href='{{url_for('design.design', _id=design.id)}}'> {{design.name}} </a>
{% if plate is not none %}
  ({{plate}})
{% endif %}
{% endblock %}

{% block controls %}

<!-- <form action="{{url_for('design.design',_id=design.id)}}" method='POST' enctype="multipart/form-data">
  <div class="form-group">
    <label for="platename">Design type</label>
    {{ designform.type(class_="form-control") }}
  </div>
  <button type="submit" id="myButton" class="btn btn-default" data-loading-text="Updating...">
     <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Update
  </button>
  <script>
    $('#myButton').on('click', function () {
      var $btn = $(this).button('loading')
    })
  </script>
</form> -->

<div class="btn-group-vertical" role="group" >
  <a href='{{url_for('design.design_edit', _id=design.id)}}' role="button" class="btn btn-success btn-large">Edit</a>
</div>

{% endblock %}

{% block noplot %}
<h2> Too many wells (> 200) for plotting </h2>
{% endblock %}

{% block beforeplot %}

<h2> {{design.name}} </h2>

<table class="table table-bordered">
  <tr>
    <td class="col-md-2"> description </td>
    <td> {{design.description}}</td>
  </tr>
  <tr>
    <td class="col-md-2"> protocol </td>
    <td> {{design.protocol}}</td>
  </tr>
  <tr>
    <td class="col-md-2"> type </td>
    <td> {{design.type}}</td>
  </tr>
  <tr>
    <td class="col-md-2"> unique values </td>
    <td> {{values.all() | length}} </td>
  </tr>
  <tr>
    <td class="col-md-2"> project </td>
    <td> <a href="{{url_for('project.project', projectid=design.project.id)}}"> {{ design.project.name|e }} </a> </td>
  </tr>

</table>
{% endblock %}

{% block afterplot %}

<div>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th class='text-center'>value</th>
        <th class='text-center'>size</th>
      </tr>
    </thead>
    <tbody>
      {% for v in values %}
          <tr>
            <td> <a href='{{url_for('misc.experimentalDesign', _id=v.id)}}'>  {{ v.value }} </a> </td>
            <td> {{ v.wells | length}} </td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

popmachine/application/templates/plate.html
{% extends "base.html" %}

{% block head %}
  <!-- td a {
   display: block;
   border: 1px solid black;
   padding: 16px;
  } -->
{% endblock %}

{% block subheading %}
{{plate.name}}
{% endblock %}

{% block controls %}
<!-- <nav class="bs-docs-sidebar hidden-print hidden-sm hidden-xs affix-top">
  <ul class="nav bs-docs-sidenav">
    <li class=""> <button type="button" class="btn btn-primary">Design</button> </li>
    <li class=""> <button type="button" class="btn btn-danger">Delete</button> </li>
  </ul>
</nav> -->

<div class="btn-group-vertical" role="group" >
  <a href='{{url_for("misc.index")}}' role="button" class="btn btn-success btn-large"> Edit </a>
  <a href='{{url_for("misc.index")}}' role="button" class="btn btn-primary btn-large"> Design </a>
  <a href='{{url_for('plate.plate_delete', platename=plate.name)}}' role="button" class="btn btn-success btn-danger">Delete</a>
</div>

{% endblock %}

{% block content %}

{% if plate %}
  <div class='container'>
    <div class='row'>
      <div class="col-md-2">
        <h4>project:</h4>
      </div>
      <div class="col-md-4">
        <a href='{{url_for('project.project',projectid=plate.project.id)}}'
          <p>{{plate.project.name}}</p>
        </a>
      </div>
    </div>
    <div class='row'>
      <div class="col-md-2">
        <h4>submission date:</h4>
      </div>
      <div class="col-md-4">
        {{plate.submission_date}}
      </div>
    </div>
    <div class='row'>
      <div class="col-md-2">
        <h4>protocol:</h4>
      </div>
      <div class="col-md-4">
        {{plate.protocol}}
      </div>
    </div>
    <div class='row'>
      <div class="col-md-2">
        <h4>wells:</h4>
      </div>
      <div class="col-md-4">
        {{plate.wells | length}}
      </div>
    </div>

    {% if designs %}
      <div class='row'>
        <div class="col-md-6">
            <h2> Designs </h2>
        </div>
      </div>
      <div class='row'>
        <div class="col-md-6">
          <table class='table table-hover'>
              <thead>
                <tr>
                  <th class='text-center'>design</th>
                  <th class='text-center'>values</th>
                </tr>
              </thead>
              <tbody>
                {% for d in designs %}
                    <tr>
                      <td class='text-center'> <a href='{{url_for('design.design', _id=d.id, plate=plate.name)}}'> {{ d.name }} </a></td>
                      <td class='text-center'>
                        {% for ed in d.values|sort(attribute='value') %}
                          <a href='{{url_for('misc.experimentalDesign', _id=ed.id, plate=plate.name)}}'> {{ ed.value }} </a>,
                        {% endfor %}
                      </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
      </div>
    </div>
    {% endif %}
{% endif %}

{% endblock %}

popmachine/application/templates/plates.html
{% extends "base.html" %}

{% block subheading %}
plates
{% endblock %}

{% block controls %}

<div class="btn-group-vertical" role="group" >
  <a href="{{url_for('plate.plate_create')}}" role='button' class="btn btn-primary btn-large">Create</a>
</div>

{% endblock %}

{% block content %}
{% if plates %}

<!-- <div class="container">
  <div class='row'>
    <div class="col-md-6"> -->

    <table class='table table-hover'>
      <thead>
        <tr>
          <th class='text-center'>plate</th>
          <th class='text-center'>project</th>
          <th class='text-center'>wells</th>
        </tr>
      </thead>
      <tbody>
        {% for plate in plates %}
            <tr>
              <td class='text-center'> <a href="{{url_for('plate.plate', platename=plate.name)}}"> {{ plate.name|e }} </a></td>
              <!-- <td class='text-center'>{{plate.project }}</td> -->
              <td class='text-center'> <a href="{{url_for('project.project', projectid=plate.project.id)}}"> {{plate.project.name }} </a></td>
              <td class='text-center'>{{plate.wells | length}}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
  <!-- </div>
</div>

</div> -->
{% endif %}
{% endblock %}

popmachine/application/templates/project-create.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block subheading %}
project create
{% endblock %}

{% block content %}

<form action="{{url_for('project.project_create')}}" method='POST' enctype="multipart/form-data">
  <div class="form-group">
    <label for="platename">name</label>
    {{ form.name(size=30,placeholder="project name", class_="form-control") }}
  </div>
  <div class="form-group">
    <label for="description">description</label>
    {{ form.description(size=200,placeholder="description of project, e.g. goals, research question", class_="form-control") }}
  </div>
  <div class="form-group">
    <label for="design">design</label>
    {{ form.design(size=400,placeholder="overall design", class_="form-control") }}
  </div>
  <div class="form-group">
    <label for="source">publish</label>
    {{ form.published(class_="form-control") }}
    <p class="help-block">Publishing a project makes it publicly available (this can be changed later).</p>
  </div>
  <div class="form-group">
    <label for="citation">citation</label>
    {{ form.citation(size=50,placeholder="citation, if applicable", class_="form-control") }}
  </div>
  <div class="form-group">
    <label for="citation_pmid">citation pubmed id</label>
    {{ form.citation_pmid(size=50,placeholder="if applicable", class_="form-control") }}
  </div>

  <button type="submit" id="myButton" class="btn btn-default" data-loading-text="Creating...">
     <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Create
  </button>
  <script>
    $('#myButton').on('click', function () {
      var $btn = $(this).button('loading')
    })
  </script>
</form>

{% endblock %}

popmachine/application/templates/search.html
{% extends "base.html" %}

{% block subheading %}
search
{% endblock %}

{% block content %}

{% endblock %}