popmachine/application/blueprints/model.py
from ..forms import SearchForm
from ..plot import plotDataset
from popmachine.models import Project, Model, Phenotype, Covariate, Test

import datetime
from sqlalchemy import not_, or_
import flask
from flask import Blueprint, current_app, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import SelectField, SelectMultipleField
from wtforms.validators import DataRequired

profile = Blueprint('model', __name__)


@profile.route('/model/<id>')
def model(id):
    if current_user.is_authenticated:
        model = current_app.machine.session.query(Model)\
            .filter_by(id=id)\
            .join(Phenotype)\
            .join(Project)\
            .filter(or_(Project.published, Project.owner == current_user)).one_or_none()
    else:
        model = current_app.machine.session.query(Model)\
            .filter_by(id=id)\
            .join(Phenotype)\
            .join(Project)\
            .filter(Project.published).one_or_none()

    if model is None:
        flask.flash('no model found or insufficient permissions!')
        flask.redirect(url_for('misc.index'))

    searchform = SearchForm()
    return render_template("model/model.html", model=model, searchform=searchform)


@profile.route('/model/create/<id>', methods=['GEt', 'POST'])
@login_required
def create(id):

    phenotype = current_app.machine.session.query(Phenotype).filter_by(
        id=id, owner=current_user).one_or_none()

    choices = [(d.name, d.name) for d in phenotype.designs]

    for i in range(len(phenotype.designs)):
        for j in range(i + 1, len(phenotype.designs)):

            d1, d2 = phenotype.designs[i], phenotype.designs[j]
            s = '%s:%s' % (d1.name, d2.name)
            choices.append((s, s))

    class ModelForm(FlaskForm):
        covariates = SelectMultipleField(
            'covariates', choices=choices)

    searchform = SearchForm()
    form = ModelForm()

    if form.validate_on_submit():

        if form.covariates.data:
            covariates = [Covariate(
                designs=[d]) for d in phenotype.designs if d.name in form.covariates.data]

            for c in form.covariates.data:
                if ':' in c:
                    designs = c.split(":")
                    covariates.append(
                        Covariate(designs=[d for d in phenotype.designs if d.name in designs]))
        else:
            covariates = []

        now = datetime.datetime.now()
        model = Model(phenotype=phenotype, covariates=covariates,
                      queue_time=now, status='queued')
        current_app.machine.session.add(model)
        current_app.machine.session.commit()

        return redirect(url_for('model.queue'))

    if not phenotype:
        flask.flash('no phenotype found or incorrect permissions!')
        return flask.redirect(url_for('misc.index'))

    return render_template('model/create.html', phenotype=phenotype, form=form, searchform=searchform)


@profile.route('/model/queue')
@login_required
def queue():
    searchform = SearchForm()
    models = current_app.machine.session.query(Model).filter_by(
        status='queued').order_by(Model.queue_time).all()

    return render_template('model/queue.html', models=models, searchform=searchform)


@profile.route('/model/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete(id):
    searchform = SearchForm()
    model = current_app.machine.session.query(
        Model).filter_by(id=id).one_or_none()
    phenotype = model.phenotype

    if not model:
        flask.flash('no model found!')
        return flask.redirect(url_for('misc.index'))

    if request.method == 'GET':
        return render_template('delete.html', searchform=searchform, name='Model %d' % model.id, url=url_for('model.delete', id=model.id))
    else:
        current_app.machine.session.delete(model)
        current_app.machine.session.commit()
        flask.flash('model deleted!')
        return flask.redirect(url_for('phenotype', id=phenotype.id))


@profile.route('/covariate/<id>')
def covariate(id):
    searchform = SearchForm()
    covariate = current_app.machine.session.query(
        Covariate).filter_by(id=id).one_or_none()

    if not covariate:
        flask.flash('no covariate found!')
        return flask.redirect(url_for('misc.index'))

    return render_template('model/covariate.html', searchform=searchform, covariate=covariate)


@profile.route('/test/create/<id>', methods=['GET', 'POST'])
@login_required
def create_test(id):

    phenotype = current_app.machine.session.query(Phenotype).filter_by(
        id=id, owner=current_user).one_or_none()

    if not phenotype:
        flask.flash('no phenotype found or incorrect permissions!')
        return flask.redirect(url_for('misc.index'))

    models = [(m.id, m.name) for m in phenotype.models]

    class TestForm(FlaskForm):
        alternative_model = SelectField(
            'alternative_model', choices=models, validators=[DataRequired()], coerce=int)
        null_model = SelectField(
            'null_model', choices=models, validators=[DataRequired()], coerce=int)

    searchform = SearchForm()
    form = TestForm()

    if form.validate_on_submit():

        am = current_app.machine.session.query(Model).filter_by(
            id=form.alternative_model.data).one_or_none()
        nm = current_app.machine.session.query(Model).filter_by(
            id=form.null_model.data).one_or_none()

        test = Test(alternative_model=am, null_model=nm, phenotype=phenotype)
        current_app.machine.session.add(test)
        current_app.machine.session.commit()

        return redirect(url_for('phenotype', id=phenotype.id))

    elif request.method == 'POST':
        flask.flash('form validation failed!')

    return render_template('model/test-create.html', phenotype=phenotype, form=form, searchform=searchform)


@profile.route('/test/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete_test(id):
    searchform = SearchForm()
    test = current_app.machine.session.query(
        Test).filter_by(id=id).one_or_none()
    phenotype = test.phenotype

    if not model:
        flask.flash('no test found!')
        return flask.redirect(url_for('misc.index'))

    if request.method == 'GET':
        return render_template('delete.html', searchform=searchform, name='Test %d' % test.id, url=url_for('model.delete_test', id=test.id))
    else:
        current_app.machine.session.delete(test)
        current_app.machine.session.commit()
        flask.flash('test deleted!')
        return flask.redirect(url_for('phenotype', id=phenotype.id))

popmachine/application/templates/model/covariate.html
{% extends 'base.html' %}

{% block subheading %}
covariate: {{covariate.name}}
{% endblock %}

{% block controls %}
{% endblock %}

{% block content %}

{% if covariate.designs %}
  <h4>Designs </h4>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th class='text-center'>design</th>
        <th class='text-center'>project</th>
        <th class='text-center'>values</th>
        <th class='text-center'>type</th>

      </tr>
    </thead>
    <tbody>
      {% for d in covariate.designs %}
          <tr>
            <td class='text-center'> <a href="{{url_for('design.design', _id=d.id)}}"> {{ d.name|e }} </a></td>
            <td class='text-center'> <a href="{{url_for('project.project', projectid=d.project.id)}}"> {{d.project.name }} </a></td>
            <td class='text-center'>{{d.values | length}}</td>
            <td class='text-center'>{{d.type }}</td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if covariate.models %}
  <h4>Models </h4>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th class='text-center'>id</th>
        <th class='text-center'>phenotype</th>
        <th class='text-center'>status</th>
        <th class='text-center'>log-likelihood</th>
      </tr>
    </thead>
    <tbody>
      {% for d in covariate.models %}
          <tr>
            <td class='text-center'> <a href="{{url_for('model.model', id=d.id)}}"> {{ d.id|e }} </a></td>
            <td class='text-center'> <a href="{{url_for('phenotype', id=d.phenotype.id)}}"> {{d.phenotype.name }} </a></td>
            <td class='text-center'>{{d.status}}</td>
            <td class='text-center'>{{d.log_likelihood}}</td>
          </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

{% endblock %}

popmachine/application/templates/model/create.html
{% extends 'base.html' %}

{% block content %}

<form action="{{url_for('model.create', id=phenotype.id)}}" method='POST' enctype="multipart/form-data">
  <div class="form-group">
    <label>covariates</label>
    {{ form.covariates(size=10,class_="form-control") }}
  </div>
  <button type="submit" id="myButton" class="btn btn-default" data-loading-text="Creating...">
     <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Create
  </button>
  <script>
    $('#myButton').on('click', function () {
      var $btn = $(this).button('loading')
    })
  </script>
</form>

{% endblock %}

popmachine/application/templates/model/model.html
{% extends 'base.html' %}

{% block controls %}
<div class="btn-group-vertical" role="group" >
  <a href='{{url_for("model.delete", id=model.id)}}' role="button" class="btn btn-danger btn-large">Delete</a>
</div>
{% endblock %}

{% block content %}
<table class="table table-bordered">
  <tr>
    <td class="col-md-2"> equation </td>
    <td> {{model.name}}</td>
  </tr>
  <tr>
    <td class="col-md-2"> covariates </td>
    <td>
      {% for d in model.covariates %}
        <!-- <a href='{{url_for('design', _id=d.id)}}'>{{d.name}}</a>, -->
        {{d.name}},
      {% endfor %}
    </td>
  </tr>
  <tr>
    <td class="col-md-2"> created by </td>
    <td> {{model.phenotype.owner.name}}</td>
  </tr>
  <tr>
    <td class="col-md-2"> project </td>
    <td> <a href="{{url_for('project.project', projectid=model.phenotype.project.id)}}"> {{model.phenotype.project.name}} </a></td>
  </tr>
  <tr>
    <td class="col-md-2"> phenotype </td>
    <td> <a href="{{url_for('phenotype', id=model.phenotype.id)}}"> {{model.phenotype.name}} </a></td>
  </tr>
  <tr>
    <td class="col-md-2"> status </td>
    <td> {{model.status}} </td>
  </tr>
  <tr>
    <td class="col-md-2"> log-likelihood </td>
    <td>
      {{model.log_likelihood}}
    </td>
  </tr>
</table>

{% endblock %}

popmachine/application/templates/model/queue.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered">
  <tr>
    <th> model </th>
    <th> phenotype </th>
    <th> queue time </th>
  </tr>
  {% for model in models %}
    <tr>
      <td > <a href='{{url_for('model.model', id=model.id)}}'> {{model.id}} </a> </td>
      <td > <a href='{{url_for('phenotype', id=model.phenotype.id)}}'> {{model.phenotype.name}} </a> </td>
      <td> {{model.queue_time}} </td>
    </tr>
  {% endfor %}
</table>

{% endblock %}

popmachine/application/templates/model/test-create.html
{% extends 'base.html' %}

{% block content %}

<form action="{{url_for('model.create_test', id=phenotype.id)}}" method='POST' enctype="multipart/form-data">
  <div class="form-group">
    <label>alternative model</label>
    {{ form.alternative_model(size=10,class_="form-control") }}
  </div>
  <div class="form-group">
    <label>null model</label>
    {{ form.null_model(size=10,class_="form-control") }}
  </div>
  <button type="submit" id="myButton" class="btn btn-default" data-loading-text="Creating...">
     <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Create
  </button>
  <script>
    $('#myButton').on('click', function () {
      var $btn = $(this).button('loading')
    })
  </script>
</form>

{% endblock %}